language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install -qq autopoint
script: ./reconf && ./configure && make -j4
notifications:
  email:
    recipients:
      - jamesodhunt@ubuntu.com
