language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y autopoint
script: ./reconf && ./configure && make -j4
notifications:
  email:
    recipients:
      - jamesodhunt@ubuntu.com
